[package]
name = "typewriter"
version = "0.1.0"
authors = ["gareykhanov <gareykhanov@i-teco.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
utf-8 = "0.7.5"
